name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
        # Dies checkt den aktuellen Code in der Pipeline aus.

      # Install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Verwende eine unterstützte Node.js-Version
        # Node.js Version 20 wird für die Kompatibilität mit React verwendet.

      # Install dependencies
      - name: Install dependencies
        run: npm install
        # Installiert alle benötigten npm-Pakete.

      # Lint the code
      - name: Run Linter
        run: npm run lint
        # Führt das in package.json definierte ESLint-Skript aus, um den Code zu überprüfen.

      # Run tests
      - name: Run Tests
        run: npm test

      # Collect test results
      - name: Upload test results
        if: always() # Testberichte werden hochgeladen, auch wenn Tests fehlschlagen.
        run: ls -la ./.github/workflows
        # Testergebnisse werden in die Pipeline hochgeladen und gespeichert.

      # Build the project
      - name: Build project
        run: npm run build
        # Führt den Build durch, um sicherzustellen, dass die Anwendung erfolgreich gebaut werden kann.

  report:
    name: Generate Report
    needs: build
    runs-on: ubuntu-latest
    if: failure()
    # Dieser Schritt wird nur bei Fehlern im vorherigen Job ausgeführt.

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Output error message
        run: echo "Pipeline failed. Check the logs for details."
        # Gibt spezifische Fehlermeldungen in der Pipeline aus.
